### ISSUE TITLE
Include some sort of post-configure hook

### ISSUE THREAD

**Issue by AdamHillier** [larq/zookeeper#89]
We got rid of `validate_configuration`; maybe it can be replaced with `__component_configured__` or something similar.

**Comment by AdamHillier** [comment]
I'm not convinced this is necessary since #109. Fields can take dynamic default values which depend on the values of other fields (by using `@Field` as a decorator). Perhaps it could be used for validation of multiple field values at once, but I kind of think that that can happen wherever the field values are consumed.

**Comment by jneeven** [comment]
> 
> 
> I'm not convinced this is necessary since #109. Fields can take dynamic default values which depend on the values of other fields (by using `@Field` as a decorator). Perhaps it could be used for validation of multiple field values at once, but I kind of think that that can happen wherever the field values are consumed.

I disagree, there are many cases in which you want to check that e.g. `len(self.list1) == len(self.list2)` and raise an exception otherwise. Having some kind of `__post__init__` as the python `dataclass` does would be **very** useful in those situations!

I agree that it's no longer necessary to make "properties" CLI overridable though.
